In [109]:
import pandas as pd

In [110]:
X_train = pd.read_csv("/Users/vijaysabhavat/Documents/Airline_ML_Project_001/Data/CleanedData/X_train.csv")

X_test = pd.read_csv("/Users/vijaysabhavat/Documents/Airline_ML_Project_001/Data/CleanedData/X_test.csv")

X_train

,Airline,Source,Destination,Total_Stops,DurHrs_Mins,D_Day,D_Month,D_Year,D_Hour,D_Minute,A_Hour,A_Minute,A_Day,A_Month,A_Year
0,Jet Airways,Banglore,New Delhi,1,435,3,6,2019,8,55,16,10,19,9,2026
1,Jet Airways,Delhi,Cochin,1,1235,24,6,2019,16,0,12,35,25,6,2026
2,IndiGo,Mumbai,Hyderabad,0,90,21,5,2019,2,35,4,5,19,9,2026
3,Jet Airways,Kolkata,Banglore,1,365,24,5,2019,16,30,22,35,19,9,2026
4,IndiGo,Delhi,Cochin,1,300,27,3,2019,5,5,10,5,19,9,2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8546,Jet Airways,Delhi,Cochin,1,1165,27,3,2019,9,0,4,25,28,3,2026
8547,Jet Airways,Kolkata,Banglore,1,400,5,9,2019,14,5,20,45,19,9,2026
8548,Multiple carriers,Delhi,Cochin,1,760,15,5,2019,12,50,1,30,16,5,2026
8549,IndiGo,Banglore,New Delhi,0,165,3,3,2019,0,40,3,25,19,9,2026
8550,Jet Airways,Delhi,Cochin,1,925,6,1,2019,13,0,4,25,6,2,2026

In [111]:
# Transformation encoding
# Ordinal Col
# one hote col
# Numerical Col

numericalCol = ['Total_Stops','DurHrs_Mins','D_Day','D_Month','D_Year','D_Hour','D_Minute','A_Hour','A_Minute','A_Day','A_Month','A_Year']
OneHotCol =['Airline','Source','Destination']

In [112]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,StandardScaler

OneHotEncoding_01 = ("One_Hot_Encoder",OneHotEncoder(sparse_output=False, drop="first", handle_unknown="ignore"),OneHotCol,)
Scaling = ("Numerical_Coluns", StandardScaler(), numericalCol)

transform_Obj = ColumnTransformer(transformers=[OneHotEncoding_01,Scaling]).set_output(transform='pandas')

transform_Obj

ColumnTransformer(transformers=[('One_Hot_Encoder',
                                 OneHotEncoder(drop='first',
                                               handle_unknown='ignore',
                                               sparse_output=False),
                                 ['Airline', 'Source', 'Destination']),
                                ('Numerical_Coluns', StandardScaler(),
                                 ['Total_Stops', 'DurHrs_Mins', 'D_Day',
                                  'D_Month', 'D_Year', 'D_Hour', 'D_Minute',
                                  'A_Hour', 'A_Minute', 'A_Day', 'A_Month',
                                  'A_Year'])])

In [113]:
X_train_trans = transform_Obj.fit_transform(X_train)
X_train_trans

,One_Hot_Encoder__Airline_Air India,One_Hot_Encoder__Airline_GoAir,One_Hot_Encoder__Airline_IndiGo,One_Hot_Encoder__Airline_Jet Airways,One_Hot_Encoder__Airline_Jet Airways Business,One_Hot_Encoder__Airline_Multiple carriers,One_Hot_Encoder__Airline_Multiple carriers Premium economy,One_Hot_Encoder__Airline_SpiceJet,One_Hot_Encoder__Airline_Trujet,One_Hot_Encoder__Airline_Vistara,...,Numerical_Coluns__D_Day,Numerical_Coluns__D_Month,Numerical_Coluns__D_Year,Numerical_Coluns__D_Hour,Numerical_Coluns__D_Minute,Numerical_Coluns__A_Hour,Numerical_Coluns__A_Minute,Numerical_Coluns__A_Day,Numerical_Coluns__A_Month,Numerical_Coluns__A_Year
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.104793,0.156228,0.0,-0.778610,1.638733,0.388908,-0.888968,0.343504,0.618212,0.0
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.275425,0.156228,0.0,0.617029,-1.304740,-0.194011,0.625952,1.309459,-0.687807,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.935394,-0.179849,0.0,-1.825339,0.568379,-1.359850,-1.191952,0.343504,0.618212,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.275425,-0.179849,0.0,0.617029,0.300791,1.263288,0.625952,0.343504,0.618212,0.0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.615457,-0.852005,0.0,-1.301975,-1.037152,-0.485471,-1.191952,0.343504,0.618212,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8546,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.615457,-0.852005,0.0,-0.604155,-1.304740,-1.359850,0.019984,1.792436,-1.993826,0.0
8547,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.878106,1.164462,0.0,0.268119,-1.037152,0.971828,1.231920,0.343504,0.618212,0.0
8548,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.255332,-0.179849,0.0,-0.080791,1.371145,-1.797040,0.322968,-0.139473,-1.123147,0.0
8549,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.104793,-0.852005,0.0,-2.174249,0.835968,-1.505580,0.019984,0.343504,0.618212,0.0
8550,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.764762,-1.524161,0.0,0.093664,-1.304740,-1.359850,0.019984,-1.749396,-2.429165,0.0

In [114]:
X_train_trans.to_csv("/Users/vijaysabhavat/Documents/Airline_ML_Project_001/Data/Trans_Data/X_train_trans.csv")

In [115]:
import joblib
joblib.dump(transform_Obj,"/Users/vijaysabhavat/Documents/Airline_ML_Project_001/Transform.pkl")

['/Users/vijaysabhavat/Documents/Airline_ML_Project_001/Transform.pkl']

In [116]:
TransFile = joblib.load("/Users/vijaysabhavat/Documents/Airline_ML_Project_001/Transform.pkl")
TransFile

ColumnTransformer(transformers=[('One_Hot_Encoder',
                                 OneHotEncoder(drop='first',
                                               handle_unknown='ignore',
                                               sparse_output=False),
                                 ['Airline', 'Source', 'Destination']),
                                ('Numerical_Coluns', StandardScaler(),
                                 ['Total_Stops', 'DurHrs_Mins', 'D_Day',
                                  'D_Month', 'D_Year', 'D_Hour', 'D_Minute',
                                  'A_Hour', 'A_Minute', 'A_Day', 'A_Month',
                                  'A_Year'])])

In [117]:
X_test_trans = TransFile.fit_transform(X_test)
X_test_trans.to_csv("/Users/vijaysabhavat/Documents/Airline_ML_Project_001/Data/Trans_Data/X_test_trans.csv")